/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/
# include<iostream>
using namespace std;
char findTheDifference(string s, string t) {
    char ans = 0;
    for(char c : s) ans ^= c ;
    for(char c : t) ans ^= c ;
    return ans;
}
int main(){
    // vector<int>v = {7,1,5,3,6,4};
    // cout<<cost(v);
    string s = "abcd";
    string t = "abcde";
    cout<<findTheDifference(s,t);
}